apiVersion: v1
kind: Service
metadata:
  name: stock-verify-backend
spec:
  selector:
    app: stock-verify-backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: stock-verify-frontend
spec:
  selector:
    app: stock-verify-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
